"""all

Revision ID: 08a216bd4d19
Revises: bf0ab5c5356e
Create Date: 2026-09-28 18:39:01.453425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a216bd4d19'
down_revision = 'bf0ab5c5356e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_digital_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.Integer(), nullable=False),
    sa.Column('signer_name', sa.String(length=150), nullable=False),
    sa.Column('signer_role', sa.String(length=60), nullable=False),
    sa.Column('statement_text', sa.Text(), nullable=False),
    sa.Column('statement_sha256', sa.String(length=64), nullable=False),
    sa.Column('signature_png', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consent_id'], ['patient_consents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_digital_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_digital_evidence_consent_id'), ['consent_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consent_digital_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_digital_evidence_consent_id'))

    op.drop_table('consent_digital_evidence')
    # ### end Alembic commands ###
